GSPREAD_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "tvoje-app",
  "private_key_id": "xxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIE...==\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit@tyrsova.iam.gserviceaccount.com",
  "client_id": "123456789",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40tyrsova.iam.gserviceaccount.com"
}
"""

SHEET_ID = "1ruHFlYa2unjW0YdIf_PwPdzyotsDbxdr8Ci6FHm9wdo"
SHEET_NAME = "Kniha hostů – Tyršova"
